### ISSUE TITLE
License not found error

### ISSUE THREAD

**Issue by zuber-bioinfo** [chbrown/argv#1]
**Method 1**
$ pip install argv
Collecting argv
  Using cached argv-0.0.3.tar.gz (6.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/zuber/miniconda3/envs/nextstrain/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mylw37xt/argv/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mylw37xt/argv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-oelvh00p
         cwd: /tmp/pip-install-mylw37xt/argv/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mylw37xt/argv/setup.py", line 11, in <module>
        license=open('LICENSE').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
**Method 2:**
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    license=open('LICENSE').read(),
FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'

**Comment by zuber-bioinfo** [comment]
I have solved the problem by manually created license file and installed manually Method 2.
